name: RSS to JSON

on:
  schedule:
    - cron: '0 * * * *'  # 매시 정각마다 실행
  workflow_dispatch:      # 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run rss-to-json action
        uses: i-valchev/rss-to-json@v1
        with:
          source: feeds.yaml
          target: docs/feed.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update RSS feed JSON'
          file_pattern: docs/feed.json
