name: Generate RSS JSONs

on:
  schedule:
    - cron: '0 * * * *'  # 매 정각
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install rss-parser
          npm install axios
          npm install js-yaml

      - name: Run RSS Parser
        run: node index.js

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update all RSS feed JSONs'
          file_pattern: docs/*.json
          token: ${{ secrets.PERSONAL_TOKEN }}
